-- SynchBoard baseline schema (V1)
--
-- This is the cutover point from Hibernate-managed DDL (`ddl-auto=update`) to
-- Flyway-managed migrations. From here on the SQL in this directory is the
-- authority for the schema; the JPA entities describe types only.
--
-- Existing databases are NOT rebuilt by this file. `spring.flyway.baseline-on-migrate`
-- stamps an already-populated database at version 1 and skips this script; it runs
-- only against a genuinely empty database (a fresh dev or CI environment).
--
-- This file is generated from the JPA entity mappings and kept honest by
-- SchemaBaselineTest, which regenerates the DDL and fails if it no longer matches.
-- Do not hand-edit it. To change the schema, add a new V2__*.sql and update the
-- entities to match — migrations are forward-only.

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table users (
    email varchar(255) not null,
    auth_provider varchar(255) not null check ((auth_provider in ('LOCAL','GOOGLE'))),
    board_background_setting varchar(255),
    board_list_view_mode varchar(10),
    canvas_chat_split_ratio integer,
    canvas_zoom_scale float(53),
    creation_date timestamp(6) not null,
    date_of_birth date,
    default_stroke_color varchar(255),
    default_stroke_width integer,
    default_tool varchar(255),
    dock_anchor varchar(20),
    email_verification_token varchar(255),
    first_name varchar(255) not null,
    gender varchar(255),
    is_chat_open boolean,
    is_dock_minimized boolean,
    last_name varchar(255),
    password varchar(255),
    phone_number varchar(255),
    preferred_language varchar(255),
    profile_picture_url varchar(255),
    provider_id varchar(255),
    reset_code varchar(6),
    reset_expiry timestamp(6),
    theme_preference varchar(10) not null,
    primary key (email)
);

create table group_boards (
    board_group_id bigint generated by default as identity,
    board_group_name varchar(255) not null,
    canvas_background_color varchar(255),
    canvas_height integer,
    canvas_width integer,
    creation_date timestamp(6) not null,
    group_description varchar(255),
    group_picture_url varchar(255),
    invite_code varchar(255) unique,
    last_modified_date timestamp(6),
    created_by_user_email varchar(255),
    primary key (board_group_id)
);

create table group_members (
    board_group_id bigint not null,
    user_email varchar(255) not null,
    is_admin boolean not null,
    join_date timestamp(6) not null,
    primary key (board_group_id, user_email)
);

create table board_objects (
    object_id bigint generated by default as identity,
    creation_timestamp timestamp(6) not null,
    instance_id varchar(255) not null,
    is_active boolean not null,
    last_edited_timestamp timestamp(6),
    object_data jsonb,
    object_type varchar(255) not null,
    board_group_id bigint not null,
    created_by_user_email varchar(255),
    last_edited_by_user_email varchar(255),
    primary key (object_id),
    unique (instance_id, board_group_id)
);

create table action_history (
    action_id bigint generated by default as identity,
    action_type varchar(255) not null,
    is_undone boolean not null,
    state_after jsonb,
    state_before jsonb,
    timestamp timestamp(6) not null,
    board_group_id bigint not null,
    object_id bigint not null,
    user_email varchar(255) not null,
    primary key (action_id)
);

create table messages (
    message_id bigint generated by default as identity,
    message_content TEXT not null,
    sender_full_name_snapshot varchar(255) not null,
    timestamp timestamp(6) not null,
    board_group_id bigint not null,
    sender_user_email varchar(255),
    primary key (message_id)
);

create table pending_registrations (
    email varchar(255) not null,
    attempts integer not null,
    created_at timestamp(6) not null,
    date_of_birth date,
    expiry_time timestamp(6) not null,
    first_name varchar(255) not null,
    gender varchar(255),
    hashed_password varchar(255) not null,
    last_name varchar(255),
    phone_number varchar(255),
    verification_code varchar(6) not null,
    primary key (email)
);

-- ---------------------------------------------------------------------------
-- Foreign keys
-- ---------------------------------------------------------------------------

alter table if exists action_history add constraint FKbgtmloy5jmvxowv4lm9xcgcp5 foreign key (user_email) references users;
alter table if exists action_history add constraint FKfjpkavcqytyk2wb1cb1uy80pv foreign key (board_group_id) references group_boards;
alter table if exists action_history add constraint FKj34x0usx6q6j7687hnhgemb7y foreign key (object_id) references board_objects;
alter table if exists board_objects add constraint FK4161yfrqkqevdpd4y51am65lf foreign key (created_by_user_email) references users;
alter table if exists board_objects add constraint FKmaj7n62d35iqls1rpi81gapew foreign key (board_group_id) references group_boards;
alter table if exists board_objects add constraint FKorn12yfdc98hlyiwh7potxtee foreign key (last_edited_by_user_email) references users;
alter table if exists group_boards add constraint FK3iobkpn9edgesgfnghyfiu4m2 foreign key (created_by_user_email) references users;
alter table if exists group_members add constraint FK3l9jhf7hg0a8sobtqwg7fx7cs foreign key (board_group_id) references group_boards;
alter table if exists group_members add constraint FKoj2cudlnp06adfwka1ij42ld1 foreign key (user_email) references users;
alter table if exists messages add constraint FKg6pj5rwl3cfnpmmdw838wxc3g foreign key (sender_user_email) references users;
alter table if exists messages add constraint FKrnv8t8xw7gkd1yox4qsdiksu2 foreign key (board_group_id) references group_boards;
